# Python 程式設計
> Numpy

## Numpy
> Numpy 簡介<br>
> Numpy Array 的基本操作<br>
> Numpy Array 的合併與切割<br>
> Numpy Array 的運算<br>
> Numpy Array 的屬性<br>
> Numpy Array 資料讀寫

### Numpy 簡介
 - 資料科學和機器學習常用的資料結構
 - 裝載相同類型資料的多維陣列
 - 較 List 高效且擁有多項功能，使用上須注意與 List 的差異
 - shape：資料維度, ex. (2,3) 代表 2x3 的矩陣
 - dtype：資料型態, 陣列中元素的型態
 - 使用前須先導入 numpy 函式庫

導入 Numpy 函式庫

In [1]:
import numpy as np

### Numpy Array 的基本操作
> 建立 Numpy Array<br>
> 取得 Numpy Array 的值<br>
> 修改 Numpy Array 的值<br>
> 刪除 Numpy Array 的值<br>
> 新增 Numpy Array 的值

#### 建立 Numpy Array

使用 List 建立 Array &rarr; np.array ( List )

In [2]:
# 一維 Array
one_dim = np.array([1,2,3])
one_dim

array([1, 2, 3])

In [3]:
# 二維 Array
two_dim = np.array([[1,2,3],[1,2,3]])
two_dim

array([[1, 2, 3],
       [1, 2, 3]])

In [4]:
# 三維 Array
three_dim = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
three_dim

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

建立全為 0 的 Array &rarr; np.zeros ( shape )

In [5]:
zero_array = np.zeros((2,3,4))
zero_array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

建立全為 1 的 Array &rarr; np.ones ( shape )

In [6]:
one_array = np.ones((2,3))
one_array

array([[1., 1., 1.],
       [1., 1., 1.]])

建立指定數值的 Array &rarr; np.full ( shape, number )

In [7]:
eight_array = np.full((2,3),8)
eight_array

array([[8, 8, 8],
       [8, 8, 8]])

建立有序數列的 Array &rarr; np.arange( start_value, end_value, skip )

In [8]:
order_array = np.arange(1,10,2)
order_array

array([1, 3, 5, 7, 9])

建立亂數 Array &rarr; np.random.random ( shape )

In [9]:
random_array =  np.random.random((2,3))
random_array

array([[0.84727494, 0.12502278, 0.99190153],
       [0.24034541, 0.76068946, 0.57566628]])

#### 取得 Numpy Array 的值

取一個值 &rarr; Array [ index ]

In [10]:
one_dim[2]

3

In [11]:
two_dim[1,1]

2

取連續值 &rarr; Array [ index1 : index2 ]

In [12]:
one_dim[0:2]

array([1, 2])

In [13]:
two_dim[:,:2]

array([[1, 2],
       [1, 2]])

用條件取值 &rarr; Array [ condition ]

In [14]:
one_dim[one_dim>1]

array([2, 3])

In [15]:
two_dim[two_dim>1]

array([2, 3, 2, 3])

#### 修改 Numpy Array 的值

Array [ index ] = value

In [16]:
two_dim[1,2] = 9
two_dim

array([[1, 2, 3],
       [1, 2, 9]])

#### 刪除 Numpy Array 的值

np.delete ( Array, [ index ] )

In [17]:
np.delete(two_dim,[0,2],axis=1)

array([[2],
       [2]])

#### 新增 Numpy Array 的值

np.insert ( Array, index, value )

In [18]:
one_dim = np.insert(one_dim,0,9)
one_dim

array([9, 1, 2, 3])

np.append ( Array, value )

In [19]:
np.append(one_dim,8)

array([9, 1, 2, 3, 8])

np.append ( Array1, Array2 )

In [20]:
array1 = np.array([9,8,7])
np.append(one_dim,array1)

array([9, 1, 2, 3, 9, 8, 7])

### Numpy Array 的合併與切割

 - 垂直方向合併：np.vstack ( ( Array1, Array2 ) )
 - 水平方向合併：np.hstack ( ( Array1, Array2 ) )

In [21]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[9,8,7]])
np.vstack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [22]:
np.hstack((array1,array2))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 8, 7]])

 - 垂直方向合併：np.concatenate ( ( Array1, Array2 ), axis = 0 )
 - 水平方向合併：np.concatenate ( ( Array1, Array2 ), axis = 1 )

In [23]:
np.concatenate((array1,array2),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [24]:
np.concatenate((array1,array2),axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 8, 7]])

 - 垂直方向分割：np.vsplit ( Array, section )
 - 水平方向分割：np.hsplit ( Array, section )

In [25]:
np.vsplit(array1,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [26]:
np.hsplit(array1,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

### Numpy Array 的運算

加 &rarr; Array1 + Array2

In [27]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array1+array2

array([5, 7, 9])

如果是 List 相加呢？

In [28]:
list1 = [1,2,3]
list2 = [4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

減 &rarr; Array1 - Array2

In [29]:
array1-array2

array([-3, -3, -3])

乘 &rarr; Array1 * Array2

In [30]:
array1*array2

array([ 4, 10, 18])

In [31]:
list1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

除 &rarr; Array1 / Array2

In [32]:
array1/array2

array([0.25, 0.4 , 0.5 ])

是否相等 &rarr; Array1 == Array2

In [33]:
array1 == array2

array([False, False, False])

如果想知道兩個 Array 是否完全相等呢？ &rarr; np.array_equal ( Array1, Array2 )

In [34]:
np.array_equal(array1,array2)

False

### Numpy 常用方法

np.sqrt ( Array )

In [35]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081])

np.log ( Array )

In [36]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])

Array.sum ( )

Array.sum ( axis = 0 )

Array.sum ( axis = 1 )

In [37]:
two_dim.sum(axis = 1)

array([ 6, 12])

Array.max ( )

Array.max ( axis = 0 )

Array.max ( axis = 1 )

In [38]:
two_dim.max(axis = 0)

array([1, 2, 9])

Array.mean ( )

Array.mean ( axis = 0 )

Array.mean ( axis = 1 )

In [39]:
two_dim.mean(axis = 1)

array([2., 4.])

另一種寫法：np.mean ( Array, axis = 0 )

In [40]:
np.mean(two_dim,axis=0)

array([1., 2., 6.])

### Numpy Array 的屬性

Array.ndim &rarr; Array 的 N 維

In [41]:
three_dim.ndim

3

Array.shape &rarr; Array 的維度

In [42]:
two_dim.shape

(2, 3)

np.reshape ( Array, shape )

In [43]:
np.reshape(two_dim, (3,2))

array([[1, 2],
       [3, 1],
       [2, 9]])

Array.size &rarr; Array 的元素個數

In [44]:
two_dim.size

6

個數是否能用 `len()` 取得？

In [45]:
len(two_dim)

2

np.resize ( Array, shape )

In [46]:
np.resize(two_dim,(3,3))

array([[1, 2, 3],
       [1, 2, 9],
       [1, 2, 3]])

Array.dtype

In [47]:
two_dim.dtype

dtype('int64')

轉換資料型態 &rarr; astype( type )