# Python 程式設計
> Pandas<br>
> Input/Output

## Final Projrct Notification
 - 考試時間：2020/01/04 15:10~18:00
 - 考試地點：原則上是大安校區，1/2會公佈
 - 考試題型：選擇題+實作題
 - 考試方式：小組討論

## Last Practice

請先 restart kernel，接著直接執行以下程式，程式結果將下載 score.npy 檔案

In [34]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1RQTtrzS5tUyzDqnK008L6mWoadEEkf5Q'
urlretrieve(url, "score.npy")

('score.npy', <http.client.HTTPMessage at 0x291b5109978>)

請用 numpy 讀取 score.npy 檔案，並將讀取結果指派給變數 score

In [35]:
import numpy as np
score = np.load('score.npy')

score 中依序紀錄了學生的姓名、國文成績、英文成績、數學成績，請問 score 中有多少個學生的資料 ?

In [36]:
score.shape[0]

568

請刪除 score 中每筆資料的學生姓名

In [160]:
score = score[:,1:]

請製作一個 Function 符合以下條件：
 - Function 名稱為 calculat_score_mean
 - 輸入參數為前題刪除完學生姓名的 score
 - 輸出為國文、英文、數學三個平均分數
 - 請使用製作好的 Function，print 出國文、英文、數學三個平均分數

In [167]:
def calculat_score_mean(score):
    score = score.astype(int)
    array = score.mean(axis=0)
    return array[0], array[1], array[2]
chines, english, math = calculat_score_mean(score)
print(chines, english, math)

50.390845070422536 50.67781690140845 50.32746478873239


## Pandas
> Pandas 簡介<br>
> Series 的建立<br>
> Series 的操作<br>
> DataFrame 的建立<br>
> DataFrame 的操作<br>
> DataFrame feat. 統計資料<br>
> DataFrame feat. 資料處理

### Pandas 簡介
 - Numpy 是以 Array 形式呈現
 - Pandas 是以 Numpy 為基礎，提供三種資料結構：Series(一維)、DataFrame(二維)、Panel(三維)
 - Series 可看成可調整 index 的 Array，使用上須注意位置和 index 的差別
 - DataFrame 可看成可調整 index 和 column 的多個 Series

導入 Pandas

In [52]:
import pandas as pd

### Series 的建立

利用 List/Array 建立 Series

In [53]:
series_a = pd.Series([1,2,3,4,5])
series_a

0    1
1    2
2    3
3    4
4    5
dtype: int64

利用 Dictionary 建立 Series

In [54]:
dict_b = {'Tom':150, 'David':180, 'Mary':170, 'Jane':160}

series_b = pd.Series(dict_b)
series_b

Tom      150
David    180
Mary     170
Jane     160
dtype: int64

取得 index

In [55]:
series_b.index

Index(['Tom', 'David', 'Mary', 'Jane'], dtype='object')

取得 values

In [56]:
series_b.values

array([150, 180, 170, 160], dtype=int64)

### Series 的操作
> Series 的取值<br>
> Series 的新增<br>
> Series 的刪除<br>
> Series 的修改

#### Series 的取值

利用 `index` 取值

In [57]:
series_a[1]

2

In [58]:
series_b['Mary']

170

一次取多值

In [59]:
series_a[0:2]

0    1
1    2
dtype: int64

In [60]:
series_a[[0,2]]

0    1
2    3
dtype: int64

利用 `.iloc[ ]` 取值 => 參數為位置

In [61]:
series_a.iloc[0]

1

In [62]:
series_a.iloc[0:2]

0    1
1    2
dtype: int64

In [63]:
series_a.iloc[[0,2]]

0    1
2    3
dtype: int64

In [64]:
series_b.iloc[0:2]

Tom      150
David    180
dtype: int64

In [27]:
series_b.iloc['Tom'] # 輸入非位置會出錯

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [Tom] of <class 'str'>

利用 `.loc[ ]` 取值 => 參數為 index

In [65]:
series_b.loc['Tom']

150

In [66]:
series_b.loc['Tom':'Mary']

Tom      150
David    180
Mary     170
dtype: int64

In [67]:
series_b.loc[['Tom','Mary']]

Tom     150
Mary    170
dtype: int64

In [36]:
series_b.loc[0] # 輸入非 index 會出錯

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

利用 `條件式` 取值

In [68]:
series_b[series_b<170]

Tom     150
Jane    160
dtype: int64

In [69]:
# 多條件時需要 (1)將每個條件括號起來 (2)使用 & | 取代 and 跟 or
series_b[(series_b>150) & (series_b<170)]

Jane    160
dtype: int64

#### Series 的新增

使用 `append( )` 新增

In [70]:
series_c = series_a.append(pd.Series([6,7,8]))
series_c

0    1
1    2
2    3
3    4
4    5
0    6
1    7
2    8
dtype: int64

In [71]:
series_c = series_a.append(pd.Series([6,7,8]), ignore_index=True)
series_c

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [73]:
# or you can use reindex()
series_c = series_a.append(pd.Series([6,7,8]))
series_c.reindex()

0    1
1    2
2    3
3    4
4    5
0    6
1    7
2    8
dtype: int64

利用 `pd.concat( [ ] )` 新增

In [74]:
series_d = pd.concat([series_a, series_b]) 
series_d

0          1
1          2
2          3
3          4
4          5
Tom      150
David    180
Mary     170
Jane     160
dtype: int64

In [75]:
series_d = pd.concat([series_a, series_b], ignore_index=True) 
series_d

0      1
1      2
2      3
3      4
4      5
5    150
6    180
7    170
8    160
dtype: int64

利用取值方式新增

In [76]:
series_c[9]=10
series_c

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
9    10
dtype: int64

#### Series 的修改

使用 `index` 修改 

In [77]:
series_b.loc['Mary'] = 190
series_b

Tom      150
David    180
Mary     190
Jane     160
dtype: int64

使用 `位置` 修改

In [78]:
series_b.iloc[0] = 190
series_b

Tom      190
David    180
Mary     190
Jane     160
dtype: int64

請問如何將 series_b 180以下的數值都改成190?

In [79]:
series_b.loc[series_b<=180] = 190
series_b

Tom      190
David    190
Mary     190
Jane     190
dtype: int64

In [80]:
dict_b = {'Tom':150, 'David':180, 'Mary':170, 'Jane':160}

series_b = pd.Series(dict_b)
series_b

Tom      150
David    180
Mary     170
Jane     160
dtype: int64

#### Series 的刪除

利用 `drop( )` 刪除 => 後面需使用 index

In [81]:
series_c = series_b.drop(['Tom','Mary'])
series_c

David    180
Jane     160
dtype: int64

In [82]:
series_c = series_b.drop(0) # 使用位置會出錯
series_c

KeyError: '[0] not found in axis'

Series 跟 Array 最大的不同是 index 的處理，有時會因此在使用上比較便利，但往往也存在替代方案。因此課堂上不會在此多作著墨，同學如有興趣可參考 [Pandas 官方文件](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html)

### DataFrame 的建立

利用 List/Array 建立 DataFrame

In [83]:
df_a = pd.DataFrame([[1,2,3],[4,5,6]])
df_a

0  1  2
0  1  2  3
1  4  5  6

建立 DataFrame 同時設定欄位

In [84]:
columns = ['a','b','c']
df_a = pd.DataFrame([[1,2,3],[4,5,6]],columns=columns)
df_a

a  b  c
0  1  2  3
1  4  5  6

利用 Dictionary 建立 DataFrame

In [85]:
dict_b = {'Height':[150,160,170,180,170,160,150,170,180,200],
          'Weight':[40,50,60,70,80,70,60,50,60,90]}

df_b = pd.DataFrame(dict_b)
df_b

Height  Weight
0     150      40
1     160      50
2     170      60
3     180      70
4     170      80
5     160      70
6     150      60
7     170      50
8     180      60
9     200      90

建立 DataFrame 同時設定 index

In [86]:
dict_b = {'Height':[150,160,170,180,170,160,150,170,180,200],
          'Weight':[40,50,60,70,80,70,60,50,60,90]}
index = ['Mary','Jane','Bob','Jack','Peter','Ben','Janet','Wind','Angle','John']

df_b = pd.DataFrame(dict_b, index=index)
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

取得欄位

In [87]:
df_b.columns

Index(['Height', 'Weight'], dtype='object')

取得 index

In [88]:
df_b.index

Index(['Mary', 'Jane', 'Bob', 'Jack', 'Peter', 'Ben', 'Janet', 'Wind', 'Angle',
       'John'],
      dtype='object')

取得 values

In [89]:
df_b.values

array([[150,  40],
       [160,  50],
       [170,  60],
       [180,  70],
       [170,  80],
       [160,  70],
       [150,  60],
       [170,  50],
       [180,  60],
       [200,  90]], dtype=int64)

取得資料筆數

In [90]:
len(df_b)

10

取得矩陣大小

In [91]:
df_b.shape # 10筆資料，2個欄位

(10, 2)

取得前五筆資料

In [92]:
df_b.head()

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80

取得末五筆資料

In [93]:
df_b.tail()

Height  Weight
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

### DataFrame 的操作
> DataFrame 的取值<br>
> DataFrame 的新增<br>
> DataFrame 的修改<br>
> DataFrame 的刪除

#### DataFrame 的取值

利用欄位取值 => 會取得整欄的資料

In [94]:
df_b['Weight']

Mary     40
Jane     50
Bob      60
Jack     70
Peter    80
Ben      70
Janet    60
Wind     50
Angle    60
John     90
Name: Weight, dtype: int64

In [95]:
df_b.Weight

Mary     40
Jane     50
Bob      60
Jack     70
Peter    80
Ben      70
Janet    60
Wind     50
Angle    60
John     90
Name: Weight, dtype: int64

利用欄位取值的型態是??

In [96]:
type(df_b['Weight'])

pandas.core.series.Series

利用`iloc[ ]`取值

In [97]:
df_b.iloc[1,1]

50

In [98]:
df_b.iloc[1:3,0:2]

Height  Weight
Jane     160      50
Bob      170      60

請問該如何用`.iloc[ ]`同時只取出 Mary 和 Jack 的身高?

In [100]:
df_b.iloc[[0,3],0]

Mary    150
Jack    180
Name: Height, dtype: int64

利用`loc[ ]`取值

In [101]:
df_b.loc['Jack','Height']

180

In [102]:
df_b.loc['Jack':'Ben','Height':'Weight']

Height  Weight
Jack      180      70
Peter     170      80
Ben       160      70

In [103]:
df_b.loc[['Jack','Mary'],'Height']

Jack    180
Mary    150
Name: Height, dtype: int64

利用 `條件式` 取值

In [104]:
df_b[df_b['Weight']>70]

Height  Weight
Peter     170      80
John      200      90

In [105]:
df_b['Height'][df_b['Weight']>70]

Peter    170
John     200
Name: Height, dtype: int64

In [106]:
condition1 = df_b['Weight']>70
condition2 = df_b['Height']>170
df_b.loc[condition1 & condition2]

Height  Weight
John     200      90

如果想轉成 List 該怎麼做?

In [107]:
list_b = df_b['Height'].values.tolist()
list_b

[150, 160, 170, 180, 170, 160, 150, 170, 180, 200]

#### DataFrame 的新增

使用 `append( )` 新增

In [108]:
df_c = df_a.append(pd.DataFrame([[7,8,9]],columns=['a','b','c']),ignore_index=True)
df_c

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

利用 `pd.concat( [ ] )` 新增

In [109]:
df_d = pd.concat([df_a,df_c],ignore_index=True)
df_d

a  b  c
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  7  8  9

利用取值方式新增

In [110]:
df_d.loc[5] = [1,2,3]
df_d

a  b  c
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  7  8  9
5  1  2  3

#### DataFrame 的修改

利用位置修改

In [111]:
df_b.iloc[0,0] = 170
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

利用 index 及 column 修改

In [112]:
df_b.loc['Angle','Weight'] = 70
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      70
John      200      90

利用條件式修改

In [113]:
condition1 = df_b['Weight']>70
condition2 = df_b['Height']>170
df_b[condition1 & condition2] = 100 # 整筆資料都會變成 100
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      70
John      100     100

In [115]:
condition1 = df_b['Weight']<70
condition2 = df_b['Height']<160
df_b['Height'][condition1 & condition2] = 180 # 只有身高會變成 180
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

#### DataFrame 的刪除

利用 `drop( )` 刪除

In [116]:
df_c = df_b.drop('Mary')
df_c

Height  Weight
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

In [117]:
df_c = df_b.drop(['Mary','Ben'])
df_c

Height  Weight
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

In [118]:
df_c = df_b.drop('Height',axis=1)
df_c

Weight
Mary       40
Jane       50
Bob        60
Jack       70
Peter      80
Ben        70
Janet      60
Wind       50
Angle      70
John      100

### DataFrame feat. 統計資料

總共出現了哪些資料 => unique( )

In [119]:
df_b['Height'].unique()

array([170, 160, 180, 100], dtype=int64)

每種資料出現的次數 => value_counts( )

In [120]:
df_b['Height'].value_counts()

170    4
180    3
160    2
100    1
Name: Height, dtype: int64

最大值與最小值 => max( )、min( )

In [121]:
df_b['Height'].max()

180

In [122]:
df_b['Height'].min()

100

總和 => sum( )

In [123]:
df_b['Height'].sum()

1640

累加值 => cumsum( )

In [124]:
df_b['Height'].cumsum()

Mary      170
Jane      330
Bob       500
Jack      680
Peter     850
Ben      1010
Janet    1190
Wind     1360
Angle    1540
John     1640
Name: Height, dtype: int64

平均值 => mean( axis )

In [125]:
df_b.mean() # 預設為垂直平均

Height    164.0
Weight     65.0
dtype: float64

In [126]:
df_b.mean(axis=1) # 水平平均

Mary     105.0
Jane     105.0
Bob      115.0
Jack     125.0
Peter    125.0
Ben      115.0
Janet    120.0
Wind     110.0
Angle    125.0
John     100.0
dtype: float64

標準差 => std( )

In [127]:
df_b.std() # 預設為垂直標準差

Height    23.664319
Weight    17.159384
dtype: float64

In [128]:
df_b.std(axis=1) # 水平標準差

Mary     91.923882
Jane     77.781746
Bob      77.781746
Jack     77.781746
Peter    63.639610
Ben      63.639610
Janet    84.852814
Wind     84.852814
Angle    77.781746
John      0.000000
dtype: float64

顯示常用的統計資料 => describe( )

In [129]:
df_b.describe()

Height      Weight
count   10.000000   10.000000
mean   164.000000   65.000000
std     23.664319   17.159384
min    100.000000   40.000000
25%    162.500000   52.500000
50%    170.000000   65.000000
75%    177.500000   70.000000
max    180.000000  100.000000

### DataFrame feat. 資料處理

#### 遺漏值處理

設定為遺漏值

In [130]:
import numpy as np
df_b.iloc[0,1] = np.nan
df_b

Height  Weight
Mary      170     NaN
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

確認是否為遺漏值 => isnull( )

In [131]:
df_b.isnull()

Height  Weight
Mary    False    True
Jane    False   False
Bob     False   False
Jack    False   False
Peter   False   False
Ben     False   False
Janet   False   False
Wind    False   False
Angle   False   False
John    False   False

確認有多少個遺漏值

In [132]:
df_b.isnull().sum()

Height    0
Weight    1
dtype: int64

In [133]:
df_b.isnull().sum().sum()

1

刪除遺漏值 => dropna( )

In [134]:
df_b.dropna()

Height  Weight
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

填補遺漏值 => fillna( )

In [135]:
df_b.fillna(0)

Height  Weight
Mary      170     0.0
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

更多關於遺漏值的處理可以參考[官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)

#### 處理重複資料

是否出現重複資料 => duplicated( )

In [136]:
df_b.duplicated() # 所有資料都一樣才會判定為重複資料

Mary     False
Jane     False
Bob      False
Jack     False
Peter    False
Ben      False
Janet    False
Wind     False
Angle     True
John     False
dtype: bool

刪除重複資料 => drop_duplicates( )

In [137]:
df_b.drop_duplicates()

Height  Weight
Mary      170     NaN
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
John      100   100.0

指定欄位的資料重複時即刪除資料

In [138]:
df_b.drop_duplicates('Height')

Height  Weight
Mary     170     NaN
Jane     160    50.0
Jack     180    70.0
John     100   100.0

#### 資料排序

將 index/column 排序 => sort_index( )

In [139]:
df_b.sort_index() # index 由小到大排序

Height  Weight
Angle     180    70.0
Ben       160    70.0
Bob       170    60.0
Jack      180    70.0
Jane      160    50.0
Janet     180    60.0
John      100   100.0
Mary      170     NaN
Peter     170    80.0
Wind      170    50.0

In [140]:
df_b.sort_index(axis=1, ascending=False) # columns 由大到小排序

Weight  Height
Mary      NaN     170
Jane     50.0     160
Bob      60.0     170
Jack     70.0     180
Peter    80.0     170
Ben      70.0     160
Janet    60.0     180
Wind     50.0     170
Angle    70.0     180
John    100.0     100

將資料排序 => sort_values( )

In [141]:
df_b.sort_values(by='Height')

Height  Weight
John      100   100.0
Jane      160    50.0
Ben       160    70.0
Mary      170     NaN
Bob       170    60.0
Peter     170    80.0
Wind      170    50.0
Jack      180    70.0
Janet     180    60.0
Angle     180    70.0

In [142]:
df_b.sort_values(by=['Height','Weight'])

Height  Weight
John      100   100.0
Jane      160    50.0
Ben       160    70.0
Wind      170    50.0
Bob       170    60.0
Peter     170    80.0
Mary      170     NaN
Janet     180    60.0
Jack      180    70.0
Angle     180    70.0

#### 資料對應

利用 `map( )` 執行資料對應

In [145]:
dig_to_cat = {100:'low', 160:'low', 170:'mid', 180:'high'}
df_b['cat'] = df_b['Height'].map(dig_to_cat)
df_b

Height  Weight   cat
Mary      170     NaN   mid
Jane      160    50.0   low
Bob       170    60.0   mid
Jack      180    70.0  high
Peter     170    80.0   mid
Ben       160    70.0   low
Janet     180    60.0  high
Wind      170    50.0   mid
Angle     180    70.0  high
John      100   100.0   low

#### 資料分箱

利用 `cut( )` 執行資料分箱

In [146]:
Height = df_b['Height']
bins = [0,150,170,180]
Height_bins = pd.cut(Height, bins)
Height_bins.value_counts().sort_index()

(0, 150]      1
(150, 170]    6
(170, 180]    3
Name: Height, dtype: int64

利用資料分箱標籤

In [147]:
Height = df_b['Height']
bins = [0,150,170,180]
labels = ['low','mid','high']
df_b['label'] = pd.cut(Height, bins, labels=labels)
df_b

Height  Weight   cat label
Mary      170     NaN   mid   mid
Jane      160    50.0   low   mid
Bob       170    60.0   mid   mid
Jack      180    70.0  high  high
Peter     170    80.0   mid   mid
Ben       160    70.0   low   mid
Janet     180    60.0  high  high
Wind      170    50.0   mid   mid
Angle     180    70.0  high  high
John      100   100.0   low   low

#### 資料轉換

利用 `apply( )` 作資料轉換

In [148]:
# step1：define function
def change_to_ft(m):
    ft = m / 30.48
    return ft

# step2：put function into apply
df_b['ft'] = df_b['Height'].apply(change_to_ft)
df_b

Height  Weight   cat label        ft
Mary      170     NaN   mid   mid  5.577428
Jane      160    50.0   low   mid  5.249344
Bob       170    60.0   mid   mid  5.577428
Jack      180    70.0  high  high  5.905512
Peter     170    80.0   mid   mid  5.577428
Ben       160    70.0   low   mid  5.249344
Janet     180    60.0  high  high  5.905512
Wind      170    50.0   mid   mid  5.577428
Angle     180    70.0  high  high  5.905512
John      100   100.0   low   low  3.280840

如何計算BMI? 需要同時運用多個欄位該怎麼做?

In [149]:
def get_BMI(row):
    height = row['Height']
    weight = row['Weight']
    BMI = weight / ((height*0.01)**2)
    return BMI

df_b['BMI'] = df_b.apply(get_BMI, axis=1)
df_b

Height  Weight   cat label        ft         BMI
Mary      170     NaN   mid   mid  5.577428         NaN
Jane      160    50.0   low   mid  5.249344   19.531250
Bob       170    60.0   mid   mid  5.577428   20.761246
Jack      180    70.0  high  high  5.905512   21.604938
Peter     170    80.0   mid   mid  5.577428   27.681661
Ben       160    70.0   low   mid  5.249344   27.343750
Janet     180    60.0  high  high  5.905512   18.518519
Wind      170    50.0   mid   mid  5.577428   17.301038
Angle     180    70.0  high  high  5.905512   21.604938
John      100   100.0   low   low  3.280840  100.000000

更多關於 Pandas 的運用可以參考 [官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#selection)

## Input/Output (I/O)
> 使用 open()<br>
> 使用 Pandas

### 使用 open()

open( 資料路徑, 讀寫狀態, (編碼方式) )

 - 資料路徑可輸入相對路徑或絕對路徑
 - 讀寫狀態有 `r` (read) / `w` (write) / `a` (append)
 - 編碼方式通常在 windows 電腦須設定為 utf8
 - 每次使用完 open( ) 記得要 close( )

In [3]:
# 請先執行以下程式下載資料
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1bIemyCvt4wQ7CD30mosFGjGWgJfhaAB1'
urlretrieve(url, "students.csv")
url = 'https://drive.google.com/uc?export=download&id=1sV1zjDKzDC59CUuJQiTbdzfr953eye4z'
urlretrieve(url, "students.xlsx")

('students.csv', <http.client.HTTPMessage at 0x2919cb0e978>)

#### 讀取資料

In [4]:
file = open('students.csv', 'r', encoding='utf8')
data = file.read()
file.close()

觀察 data 長什麼樣子

In [5]:
data

'Jane,160,50\nBob,170,60\nJack,170,80\nPeter,170,80\nBen,160,70\nJanet,150,60\nWind,170,50\nAngle,180,90\n'

如何整理讀到的 data

In [6]:
lines = data.splitlines()
names = []
height = []
weight = []
for line in lines:
    items = line.split(',')
    names.append(items[0])
    height.append(items[1])
    weight.append(items[2])

In [7]:
names

['Jane', 'Bob', 'Jack', 'Peter', 'Ben', 'Janet', 'Wind', 'Angle']

In [8]:
height

['160', '170', '170', '170', '160', '150', '170', '180']

In [9]:
weight

['50', '60', '80', '80', '70', '60', '50', '90']

#### 寫入資料

In [10]:
file = open('names.txt', 'w', encoding='utf8') # 資料夾會出現 names.txt
data = file.write('\n'.join(names))
file.close()

#### 增加資料

In [11]:
file = open('names.txt', 'a', encoding='utf8')
data = file.write('Rachel')
file.close()

#### 實在覺得 close( ) 很煩，可以試試 with

In [13]:
# with 會在程式執行完後自動 close
with open('students.csv', 'r', encoding='utf8') as file:
    names = []
    height = []
    weight = []
    for line in file.read().splitlines():
        items = line.split(',')
        names.append(items[0])
        height.append(items[1])
        weight.append(items[2])

### 使用 Pandas

#### 讀取資料

In [28]:
df_csv = pd.read_csv('students.csv', header=None)
df_csv

0    1   2
0   Jane  160  50
1    Bob  170  60
2   Jack  170  80
3  Peter  170  80
4    Ben  160  70
5  Janet  150  60
6   Wind  170  50
7  Angle  180  90

In [29]:
df_xls = pd.read_excel('students.xlsx', sheet_name='工作表1', header=None)
df_xls

0    1   2
0   Jane  160  50
1    Bob  170  60
2   Jack  170  80
3  Peter  170  80
4    Ben  160  70
5  Janet  150  60
6   Wind  170  50
7  Angle  180  90

#### 寫入資料

In [20]:
df_csv.to_csv('new_students.csv')

In [21]:
df_xls.to_excel('new_students.xlsx')

更多 Pandas 讀取資料格式可以參考[官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

## Practice

請先 restart kernel，接著直接執行以下程式，程式結果將下載 iris.csv 檔案

In [22]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1aEdeQhML2zOAhiMQ1UL1qQPY7DdWgGlx'
urlretrieve(url, "iris.csv")

('iris.csv', <http.client.HTTPMessage at 0x291b50dea58>)

請使用 open( ) 讀取 iris.csv，請 print 出 '共有 ? 筆資料, ? 個欄位'

In [26]:
with open('iris.csv', 'r') as file:
    data = file.read().splitlines()
    len_data = len(data)
    len_column = len(data[0].split(','))
    print('共有{}筆資料,{}個欄位'.format(len_data,len_column))

共有150筆資料,5個欄位


請使用 Pandas 讀取 iris.csv，將讀取到的 DataFrame 指派給變數 iris，並顯示前五筆資料

In [31]:
import pandas as pd
iris = pd.read_csv('iris.csv', header=None)
iris.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

請問資料中共有幾筆遺漏值?

In [32]:
iris.isnull().sum().sum()

4

請將遺漏值刪除，並 print 出 '刪除遺漏值後資料筆數為 ? 筆'

In [38]:
iris = iris.dropna()
len_iris = len(iris)
print('刪除遺漏值後資料筆數為{}筆'.format(len_iris))

刪除遺漏值後資料筆數為146筆


請將資料新增四個欄位，分別為欄位一到欄位四的 dummy variable (小於欄位平均數為 0，大於等於欄位平均數為 1)

In [42]:
def dummy_variable(iris, column):
    mean_value = iris[column].mean()
    max_value = iris[column].max()
    bins = [0, mean_value, max_value]
    labels = [0, 1]
    column_name = column + 5
    iris[column_name] = pd.cut(iris[column], bins, labels=labels)
    return iris

In [46]:
for col in range(4):
    iris = dummy_variable(iris, col)
iris.head()

0    1    2    3            4  5  6  7  8
0  5.1  3.5  1.4  0.2  Iris-setosa  0  1  0  0
1  4.9  3.0  1.4  0.2  Iris-setosa  0  0  0  0
2  4.7  3.2  1.3  0.2  Iris-setosa  0  1  0  0
3  4.6  3.1  1.5  0.2  Iris-setosa  0  1  0  0
4  5.0  3.6  1.4  0.2  Iris-setosa  0  1  0  0

請將新增的四欄轉成 Numpy Array，並指派給變數 train_x

In [50]:
train_x = iris.loc[:,5:8].values
train_x[:5]

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]], dtype=object)

請再將資料新增一個欄位，把第五欄的資料的 Iris-setosa -> 0, Iris-versicolor-> 1, Iris-virginica -> 2

In [47]:
cat_to_dig = {'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2}
iris[9] = iris[4].map(cat_to_dig)
iris.head()

0    1    2    3            4  5  6  7  8  9
0  5.1  3.5  1.4  0.2  Iris-setosa  0  1  0  0  0
1  4.9  3.0  1.4  0.2  Iris-setosa  0  0  0  0  0
2  4.7  3.2  1.3  0.2  Iris-setosa  0  1  0  0  0
3  4.6  3.1  1.5  0.2  Iris-setosa  0  1  0  0  0
4  5.0  3.6  1.4  0.2  Iris-setosa  0  1  0  0  0

請將新增的一欄轉成 Numpy Array，並指派給變數 train_y

In [51]:
train_y = iris[9].values
train_y[:5]

array([0, 0, 0, 0, 0], dtype=int64)

請將下載成 `html 檔`，檔名為 `學號_姓名`，上傳到 my2 作業區 