# Python 程式設計
> Function<br>
> Numpy

## Final Projrct Notification
 - 考試時間：2020/01/04 15:10~18:00
 - 考試方式：兩人一組
 - 考試題型：類似每次上課的練習
 - 請 12/27 23:59 前到下面 link 填寫分組名單，未填寫則隨機分組
 - [link](https://docs.google.com/forms/d/e/1FAIpQLSc5Exbez5uO4HG6zLFZMkfEi2wUxnZQyK3Afukk_0OvZaWeiQ/viewform?usp=sf_link)

## Mid-term Exam

#### WillyPillow 正在學習 Python 程式設計，在安裝完 `Python3` 之後，寫了五個小程式，但寫完後不知道哪裡錯了，請幫他個忙，讓他的程式能夠正常運作。

1. WillyPillow 想要撰寫一個英文星期轉換中文星期的程式，例如輸入『Monday』會輸出『星期一』。

In [ ]:
day = input()

if day = 'Monday'
    print 星期一
elif day = 'Tuesday'
    print 星期二
elif day = 'Wednesday'
    print 星期三
elif day = 'Thursday'
    print 星期四
elif day = 'Friday'
    print 星期五
elif day = 'Saturday'
    print 星期六
elif day = 'Sunday'
    print 星期日

In [ ]:
day = input()

if day == 'Monday':
    print ('星期一')
elif day == 'Tuesday':
    print ('星期二')
elif day == 'Wednesday':
    print ('星期三')
elif day == 'Thursday':
    print ('星期四')
elif day == 'Friday':
    print ('星期五')
elif day == 'Saturday':
    print ('星期六')
elif day == 'Sunday':
    print ('星期日')

2. WillyPillow 想撰寫一個程式計算 1~20000 中所有偶數的總和。

In [ ]:
for number in range(20000):
    total = 0
    if number % 2 == 0
        total + number
print total

In [ ]:
total = 0
for number in range(1,20001):
    if number % 2 == 0:
        total += number
print (total)

3. WillyPillow 想撰寫一個程式將一段文章用換行符號斷句，並判斷每個句子中是否有出現 WillyPillow 的名字。如句子中有出現 WillyPillow，則印出出現的次數，如未出現則不印出出現次數。

In [ ]:
sentences = '''WillyPillow is learning Python.
WillyPillow feels Python is fun.
It needs time to improve Python.
WillyPillow named his PC WillyPillow PC.
WillyPillow WillyPillow WillyPillow ... do not hate WillyPillow'''

for sentence in snetences.split():
    if 'WillyPillow' in sentence:
        words = sentence.split()
    print sentence + '：出現 WillyPillow ' + words.count('WillyPillow') + ' 次'

In [ ]:
sentences = '''WillyPillow is learning Python.
WillyPillow feels Python is fun.
It needs time to improve Python.
WillyPillow named his PC WillyPillow PC.
WillyPillow WillyPillow WillyPillow ... do not hate WillyPillow'''

for sentence in sentences.split('\n'):
    if 'WillyPillow' in sentence:
        words = sentence.split()
        print (sentence + '：出現 WillyPillow ' + str(words.count('WillyPillow')) + ' 次')

4. WillyPillow 想撰寫一個程式計算陣列 (List) 中數值的平均數。

In [ ]:
numbers = [5,3,7,2,8]
total = numbers.sum()
mean = total / length(numbers)
print mean

In [ ]:
numbers = [5,3,7,2,8]
total = sum(numbers)
mean = total / len(numbers)
print (mean)

5. WillyPillow 想撰寫一個程式印出儲存於 Dictionary 的電影資料。

In [ ]:
movie = {'name': 'Gemini Man', 
         'director': 'Ang Lee', 
         'Starring': 'Will Smith', 
         'Running time':117}
for k,v in movie:
    print k+'：'+v

In [ ]:
movie = {'name': 'Gemini Man', 
         'director': 'Ang Lee', 
         'Starring': 'Will Smith', 
         'Running time':117}
for k,v in movie.items():
    print (k+'：'+str(v))

## Last Practice
>製作一段文章的字數字典

In [ ]:
paragraph = '''
『木頭物語』

妳老跟朋友抱怨我像根木頭
我聽說後，總是笑笑的不以為意
我不善於流露出我的情感
實著是怯於顯露出吧
我只想把妳照顧好
在妳喊餓時
跑去一公里外的那家妳最愛吃的麵店
買份妳最愛吃的乾麵
靜靜的陪妳吃完
電話中妳說妳病了
連忙甩掉手中的實驗報告
跑到妳的住處照顧妳

妳常安慰自己
我的木頭是因為理性蓋過了感性
況且木頭也沒啥不好
因為沒有別的女生會愛上一個木頭
我聽了之後仍舊是笑了笑
星空下，妳突然提到曼妮的男朋友帶她去看去看星星時
對她說的情話 讓我不得不嚥下差點出口的星體運行現象

東區的JoJo裡
妳興奮的拿起一件新款外套試穿時
我正在猜想它是由哪些材料複合而成
到台中的自強號上
妳認真的問我「到底愛不愛我？」
我對突如其來的問題感到不知所措
只好不斷地傻笑

大雨的那個晚上
妳說妳餓了而且有事對我說
於是我撐著傘
從一公里外的那家麵店
提回一碗乾麵
陪著妳吃完那碗麵
妳慢慢地對我說：『我覺得你一點也不愛我，你不能給我想要的感覺，我們分開一陣子 好不好？』
我還是輕輕的笑了笑
靜靜的走回我的住處
留下那把傘在妳的門口

我仍每天穿梭於實驗室和教室間
埋首於課本和實驗數據中
沒人發現妳離開了我
同學們只發現我花更長的時間在課本上
一個月後的一個雨天
抓著剛做出的實驗數據
衝回宿舍 在門口看見濕淋淋的妳
下意識的脫下外套包住妳
妳突然緊抱著我
哽咽地說：「木頭，對不起」
這次妳看不見我笑了笑 因為，我哭了

人因為有選擇，所以變得違反規則
一般人生活在現今繁榮的經濟體系下，在任何人、事、物中都有很多的選擇，也因為有太多的選擇，所以舉棋不定、猶豫不決變成了大部份人的習慣。

當你看著別桌跟你吃的不一樣時，你可能開始懷疑是不是他們的比較好吃？

所以每當拿起菜單目錄看到林林總總一大推的菜名，你只好又開始舉棋不定啦！

當你看到朋友、同學日子過的不錯，你可能開始懷疑自己是不是入錯行、選錯公司了,於是三心二意、工作不力，下場只好每況愈下。 

當你逛街看到美女、辣妹，你可能懷疑自己是不是娶錯老婆、交錯女朋友？

回家便沒好臉色看！感情怎麼會好？ 
也因為選擇多了，更容易使自己迷失、不知道自己要的是什麼？

記得有一次諮商一對夫妻，過程中我問老公︰『假如這輩子你只能買一部喜歡的車，也不能換，那你會如何保養這部車？』

老公很興奮的說︰『那我會用最好的機油、準時保養、常常洗車........。』

我邊點頭微笑邊聽他講了一大堆，這時我又問︰『那假如這輩子你只能娶一個老婆，也不能換，那你會如何對待她？』

這時老公臉一紅，摟著老婆伸手跟我握手說︰『我知道答案了！』

一瞬間老公看老婆的眼神都變了。
有時侯沒有選擇會比有選擇好！
在今天你如何重新面對你的工作？你的另一半？

~~如果沒有選擇。
生命是一連串孤立的片刻。
靠著回憶和幻想，許多意義浮現了，在消失與浮現不斷的重複之中獲得解放與安慰。
好好珍惜身邊的人哦........

『在身邊默默為你付出的人往往都不懂得珍惜
就是因為有了選擇才會錯過身邊的寶』
'''

# https://www.wagor.tc.edu.tw/doc/articles/0023.htm

1. 請將 paragraph 變成 unigram ('木', '頭', ...)

In [ ]:
unigram = list(paragraph)

2. 請找出 paragraph 有那些不重複字 ('木', '頭', ...)

In [ ]:
words = set(paragraph)

3. 請計算每個不重複字在 paragraph 中出現幾次，並存成 Dictionary<br>
count_dict = {'木':1, '頭':2, ...}

In [ ]:
count_dict = dict()
for word in words:
    count_dict[word] = unigrame.count(word)

In [ ]:
count_dict = dict()
for word in unigram:
    if word not in count_dict:
        count_dict[word] = 1
    else:
        count_dict[word] += 1

## Function
 - 簡化重複作業撰寫
 - 增加程式的可讀性
 - $f(x) = y$

### Create function
 - name(函式名稱)、parameters(參數)、return(傳回值)
 - parameters、return are optional

In [ ]:
def function_name(parameters):
    statement
    return value

In [ ]:
x = 1
def add(x):
    x+=1
    return x

### Call function
 - no return value
 - return value：需要指定變數

In [ ]:
value = function_name(parameters)

In [ ]:
y = add(x)
y

### Parameters
>指定參數<br>
>沒有參數<br>
>不定參數<br>
>預設參數

#### 指定參數

In [19]:
def calculate_sum(number1, number2, number3):
    sum_number = 0
    sum_number += number1
    sum_number += number2
    sum_number += number3
    return sum_number

sum_number = calculate_sum(1,2,3)
sum_number

6

#### 沒有參數
 - 沒有參數的函式，通常是用於增加程式的可讀性

In [20]:
def calculate_sum():
    sum_number = 0
    sum_number += 1
    sum_number += 2
    sum_number += 3
    return sum_number

sum_number = calculate_sum()
sum_number

6

#### 不定參數

In [16]:
def calculate_sum(*numbers):
    sum_number = 0
    for number in numbers:
        sum_number += number
    return sum_number

sum_number = calculate_sum(1,2,3)
sum_number

0

In [18]:
# 一定要輸入一個數字
def calculate_sum(number_1, *numbers):
    sum_number = number_1
    for number in numbers:
        sum_number += number
    return sum_number

sum_number = calculate_sum(1,2,3)
sum_number

6

#### 預設參數
 - 遇到沒有輸入參數時，程式自動給參數
 - 預設參數須放至後方

In [21]:
def calculate_sum(number1=1, number2=2, number3=3):
    sum_number = 0
    sum_number += number1
    sum_number += number2
    sum_number += number3
    return sum_number

sum_number = calculate_sum()
sum_number

6

In [22]:
def calculate_sum(number1=1, number2=2, number3=3):
    sum_number = 0
    sum_number += number1
    sum_number += number2
    sum_number += number3
    return sum_number

sum_number = calculate_sum(2)
sum_number

7

In [23]:
def calculate_sum(number1=1, number2=2, number3=3):
    sum_number = 0
    sum_number += number1
    sum_number += number2
    sum_number += number3
    return sum_number

sum_number = calculate_sum(number3=5)
sum_number

8

In [1]:
def calculate_sum(number1=1, number2=2, number3):
    sum_number = 0
    sum_number += number1
    sum_number += number2
    sum_number += number3
    return sum_number

sum_number = calculate_sum(number3=5)
sum_number

SyntaxError: non-default argument follows default argument (<ipython-input-1-0257135cf63c>, line 1)

### Return
 - 要傳回值時，記得要加 return，
 - 如果傳回值需要保存，記得要指定給一個變數
 - 程式遇到 return 就停止執行後面的函式內容

判斷輸入值是否為正數，是的話回傳 True，不是的話回傳 False

In [1]:
def is_positive(x):
    if x > 0:
        return True
    return False
is_positive(-3)

False

可以同時 return 多個資料

In [ ]:
def calculate_sum(number1, number2, number3):
    sum_number = 0
    sum_number += number1
    sum_number += number2
    sum_number += number3
    return sum_number, number1

sum_number, number1 = calculate_sum(1,2,3)
print(sum_number, number1)

### 全域變數 (Global variable) 與 區域變數 (Local variable)
 - 函式裡面宣告的變數為區域變數，出了函式就見光死
 - 函式外的變數為全域變數，函式可以拿來用

製作一個計算平均值的函式

In [26]:
def calculate_mean(x1, x2, x3):
    total = 0
    total += x1
    total += x2
    total += x3
    mean = total / 3
    return mean
mean = calculate_mean(1,2,3)
mean

2.0

In [27]:
total

NameError: name 'total' is not defined

In [2]:
total = 0

def calculate_mean(x1, x2, x3):
    global total
    total += x1
    total += x2
    total += x3
    mean = total / 3
    return mean
mean = calculate_mean(1,2,3)
mean

2.0

In [3]:
total

6

### Reference
 - https://www.w3schools.com/python/python_functions.asp
 - https://www.runoob.com/python/python-functions.html

## Numpy
> Numpy 簡介<br>
> Numpy Array 的基本操作<br>
> Numpy Array 的合併與切割<br>
> Numpy Array 的運算<br>
> Numpy Array 的屬性<br>
> Numpy Array 資料讀寫

### Numpy 簡介
 - 資料科學和機器學習常用的資料結構
 - 裝載相同類型資料的多維陣列
 - 較 List 高效且擁有多項功能，使用上須注意與 List 的差異
 - shape：資料維度, ex. (2,3) 代表 2x3 的矩陣
 - dtype：資料型態, 陣列中元素的型態
 - 使用前須先導入 numpy 函式庫

導入 Numpy 函式庫

In [6]:
import numpy as np

### Numpy Array 的基本操作
> 建立 Numpy Array<br>
> 取得 Numpy Array 的值<br>
> 修改 Numpy Array 的值<br>
> 新增 Numpy Array 的值<br>
> 刪除 Numpy Array 的值

#### 建立 Numpy Array

使用 List 建立 Array => np.array ( List )

In [5]:
# 一維 Array
one_dim = np.array([1,2,3])
one_dim

array([1, 2, 3])

In [7]:
# 二維 Array
two_dim = np.array([[1,2,3],[4,5,6]])
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 三維 Array
three_dim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,8,7]]])
three_dim

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]]])

建立全為 0 的 Array => np.zeros ( shape )

In [13]:
zero_array = np.zeros((2,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

建立全為 1 的 Array => np.ones ( shape )

In [14]:
one_array = np.ones((2,3,4))
one_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

建立指定數值的 Array => np.full ( shape, number )

In [16]:
eight_array = np.full((2,3),8)
eight_array

array([[8, 8, 8],
       [8, 8, 8]])

建立有序數列的 Array => np.arange( start_value, end_value, skip )

In [20]:
order_array = np.arange(0, 10, 2)
order_array

array([0, 2, 4, 6, 8])

建立亂數 Array => np.random.random ( shape )

In [22]:
random_array = np.random.random ((2,3))
random_array

array([[0.08417025, 0.35170044, 0.97936443],
       [0.65116925, 0.91457975, 0.12983548]])

#### 取得 Numpy Array 的值

Array [ index ]

In [24]:
one_dim[2]

3

In [26]:
two_dim[1,2]

6

Array [ index1 : index2 ]

In [27]:
one_dim[:2]

array([1, 2])

In [28]:
two_dim[:2,:2]

array([[1, 2],
       [4, 5]])

Array [ condition ]

In [31]:
one_dim[one_dim > 1]

array([2, 3])

In [32]:
two_dim[two_dim > 1]

array([2, 3, 4, 5, 6])

#### 修改 Numpy Array 的值

Array [ index ] = value

In [33]:
one_dim[0] = 9
one_dim

array([9, 2, 3])

In [9]:
two_dim[1,2] = 9
two_dim

array([[1, 2, 3],
       [4, 5, 9]])

#### 刪除 Numpy Array 的值

np.delete ( Array, [ index ] )

In [40]:
np.delete(one_dim, [1])

array([9, 3])

In [10]:
np.delete(two_dim, [0], axis=0)

array([[4, 5, 9]])

In [11]:
np.delete(two_dim, [0], axis=1)

array([[2, 3],
       [5, 9]])

#### 新增 Numpy Array 的值

np.insert ( Array, index, value )

In [38]:
np.insert(one_dim, 0, 5)

array([5, 9, 2, 3])

np.append ( Array, value )

In [34]:
one_dim = np.append(one_dim, 7)
one_dim

array([9, 2, 3, 7])

np.append ( Array1, Array2 )

In [36]:
np.append(zero_array, one_array)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Numpy Array 的合併與切割

 - 垂直方向合併：np.vstack ( ( Array1, Array2 ) )
 - 水平方向合併：np.hstack ( ( Array1, Array2 ) )

In [47]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[9,8,7]])
array3 = np.vstack((array1, array2))
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [48]:
array4 = np.hstack((array1, array2))
array4

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 8, 7]])

 - 垂直方向合併：np.concatenate ( ( Array1, Array2 ), axis = 0 )
 - 水平方向合併：np.concatenate ( ( Array1, Array2 ), axis = 1 )

In [49]:
array5 = np.concatenate((array1, array2), axis = 0)
array5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [51]:
array6 = np.concatenate((array1, array2), axis = 1)
array6

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 8, 7]])

 - 垂直方向分割：np.vsplit ( Array, section )
 - 水平方向分割：np.hsplit ( Array, section )

In [52]:
array7 = np.vsplit(array1, 2)
array7

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [54]:
array8 = np.hsplit(array1, 3)
array8

[array([[1],
        [4]]), array([[2],
        [5]]), array([[3],
        [6]])]

### Numpy Array 的運算

Array1 + Array2

In [62]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array1+array2

array([5, 7, 9])

In [63]:
list1 = [1,2,3]
list2 = [4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

Array1 - Array2

In [64]:
array1-array2

array([-3, -3, -3])

Array1 * Array2

In [65]:
array1 * array2

array([ 4, 10, 18])

In [66]:
list1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

Array1 / Array2

In [67]:
array1/array2

array([0.25, 0.4 , 0.5 ])

Array1 == Array2

In [68]:
array1 == array2

array([False, False, False])

np.array_equal ( Array1, Array2 )

In [69]:
np.array_equal (array1, array2)

False

np.sqrt ( Array )

In [70]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081])

np.log ( Array )

In [71]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])

Array.sum ( )

In [79]:
array3 = np.array([[1,2,3],[4,5,6]])
array3.sum()

21

Array.sum ( axis = 0 )

In [80]:
array3.sum(axis = 0)

array([5, 7, 9])

Array.sum ( axis = 1 )

In [81]:
array3.sum(axis = 1)

array([ 6, 15])

Array.max ( )

In [84]:
array3.max()

6

Array.max ( axis = 0 )

In [83]:
array3.max(axis = 0)

array([4, 5, 6])

Array.max ( axis = 1 )

In [85]:
array3.max(axis = 1)

array([3, 6])

Array.mean ( )

In [88]:
array3.mean()

3.5

Array.mean ( axis = 0 )

In [89]:
array3.mean(axis = 0)

array([2.5, 3.5, 4.5])

Array.mean ( axis = 1 )

In [90]:
array3.mean(axis = 1)

array([2., 5.])

另一種寫法：np.mean ( Array, axis = 0 )

In [86]:
array3.mean()

3.5

### Numpy Array 的屬性

Array.ndim => Array 的 N 維

In [94]:
array3.ndim

2

Array.shape => Array 的維度

In [101]:
array3.shape

(2, 3)

np.reshape ( Array, shape )

In [112]:
np.reshape(array3, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
np.reshape(array3, (3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

Array.size => Array 的元素個數

In [97]:
array3.size

6

In [100]:
len(array3)

2

Array.resize ( shape )

In [114]:
np.resize(array3, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
np.resize(array3, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

Array.dtype

In [116]:
array3.dtype

dtype('int32')

Array.astype ( DataType )

In [123]:
array3.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

### Numpy Array 資料讀寫 (I/O)

儲存 Numpy 資料格式檔案 => np.save ( file_name, Array )

In [124]:
np.save('my_array', array1) # my_array.npy

讀取 Numpy 資料格式檔案 => np.load ( file_name )

In [126]:
array_load = np.load('my_array.npy')
array_load

array([1, 2, 3])

### Reference
 - https://numpy.org/
 - https://medium.com/python4u/hello-numpy-b5ebe67a1ada
 - http://cs231n.github.io/python-numpy-tutorial/
 - https://www.delftstack.com/zh-tw/tutorial/python-numpy/numpy-array-reshape-and-resize/

## Practice

請先 restart kernel，接著直接執行以下程式，程式結果將下載 score.npy 檔案

In [156]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1RQTtrzS5tUyzDqnK008L6mWoadEEkf5Q'
urlretrieve(url, "score.npy")

('score.npy', <http.client.HTTPMessage at 0x1d2746adcc0>)

請用 numpy 讀取 score.npy 檔案，並將讀取結果指派給變數 score

In [157]:
import numpy as np
score = np.load('score.npy')

score 中依序紀錄了學生的姓名、國文成績、英文成績、數學成績，請問 score 中有多少個學生的資料 ?

In [158]:
score.shape

(568, 4)

請刪除 score 中每筆資料的學生姓名

In [160]:
score = score[:,1:]

請製作一個 Function 符合以下條件：
 - Function 名稱為 calculat_score_mean
 - 輸入參數為前題刪除完學生姓名的 score
 - 輸出為國文、英文、數學三個平均分數
 - 請使用製作好的 Function，print 出國文、英文、數學三個平均分數

In [167]:
def calculat_score_mean(score):
    score = score.astype(int)
    array = score.mean(axis=0)
    return array[0], array[1], array[2]
chines, english, math = calculat_score_mean(score)
print(chines, english, math)

50.390845070422536 50.67781690140845 50.32746478873239


請將下載成 `html 檔`，檔名為 `學號_姓名`，上傳到 my2 作業區 